#pragma once

#include <stdint.h>

struct euicc_state {
    char eid[33];                    // 32 hex chars + null terminator
    char default_smdp[256];          // Default SM-DP+ address
    char root_smds[256];             // Root SM-DS address
    int logic_channel;               // Current logical channel ID
    uint8_t aid[16];                 // Currently opened AID
    uint8_t aid_len;                 // AID length
    
    // Authentication state
    uint8_t euicc_challenge[16];     // Random challenge generated by eUICC
    uint8_t server_challenge[16];    // Challenge from SM-DP+
    uint8_t transaction_id[16];      // Transaction ID from SM-DP+
    uint8_t transaction_id_len;      // Transaction ID length
    
    // Certificates and keys (loaded from files or hardcoded for testing)
    uint8_t *euicc_cert;             // CERT.EUICC.ECDSA (DER format)
    uint32_t euicc_cert_len;
    uint8_t *eum_cert;               // CERT.EUM.ECDSA (DER format)
    uint32_t eum_cert_len;
    uint8_t *euicc_private_key;      // SK.EUICC.ECDSA (for Phase 2)
    uint32_t euicc_private_key_len;
    
    // Command segmentation buffer
    uint8_t *segment_buffer;         // Buffer for accumulating command segments
    uint32_t segment_buffer_len;     // Current length of buffered data
    uint32_t segment_buffer_capacity; // Allocated capacity
    
    // Download session tracking
    int bpp_commands_received;       // Count of BPP commands received
    uint32_t notification_seq_number; // Sequence number for notifications
    char matching_id[256];           // MatchingID from download request

    // Profile package storage (Bound Profile Package)
    uint8_t *bound_profile_package;   // Encrypted profile package data
    uint32_t bound_profile_package_len; // Length of BPP data
    uint32_t bound_profile_package_capacity; // Allocated capacity

    // Installed profiles storage (for demo purposes)
    uint8_t *installed_profiles;      // Simple storage of installed profile data
    uint32_t installed_profiles_len;  // Length of installed data
    uint32_t installed_profiles_capacity; // Allocated capacity
};

// Initialize virtual eUICC state with default values
void euicc_state_init(struct euicc_state *state);

// Reset state
void euicc_state_reset(struct euicc_state *state);

// Load certificates from files (for Phase 2)
int euicc_state_load_certificates(struct euicc_state *state, const char *cert_dir);

